coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%   # allow small project drops
    patch:
      default:
        target: auto
        threshold: 2%
        informational: true
